version: '3.5'

services:

  php-fpm:
    container_name: docker-php-fpm-example-${APP_ENV}
    build:
      context: .
      target: ${APP_ENV}
      dockerfile: .docker/php-fpm/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    volumes:
      - ./:/var/www/html:rw
      - ~/.composer:/root/.composer/cache
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"

  nginx:
    container_name: docker-nginx-example-${APP_ENV}
    build:
      context: .
      target: ${APP_ENV}
      dockerfile: .docker/nginx/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    volumes:
      - ./:/var/www/html:rw
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php-fpm