version: '3.5'

services:

  php-fpm:
    container_name: erc-php-fpm-${APP_ENV}
    build:
      context: .
      target: ${APP_ENV}
      dockerfile: .docker/php-fpm/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    volumes:
    - ./:/var/www/html:rw
    - ~/.composer:/root/.composer/cache

  nginx:
    container_name: erc-nginx-${APP_ENV}
    build:
      context: .
      target: ${APP_ENV}
      dockerfile: .docker/nginx/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    volumes:
    - ./:/var/www/html:rw
    ports:
    - ${NGINX_PORT}:80
    depends_on:
    - php-fpm